language: scala
jdk: oraclejdk8
scala: dummy # using crossScalaVersions over TRAVIS_SCALA_VERSION
script:
 - cd sbt-sample
 - sbt +update
 - cd -
 - cd maven-sample
 - mvn -Pscala-2.10 clean compile package
 - mvn -Pscala-2.10 exec:java -Dexec.mainClass=XMLHelloWorld
 - mvn -Pscala-2.11 clean compile package
 - mvn -Pscala-2.11 exec:java -Dexec.mainClass=XMLHelloWorld
 - mvn -Pscala-2.12 clean compile package
 - mvn -Pscala-2.12 exec:java -Dexec.mainClass=XMLHelloWorld

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.m2

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  - find $HOME/.m2         -name "*.lastUpdated"        -print -delete
